all:
	(cd timerLib && make install)
	(cd blink_lights && make)
	(cd button_demo && make)
	(cd buzzer_demo && make)

clean:
	(cd timerLib && make clean)
	(cd blink_lights && make clean)
	(cd button_demo && make clean)
	(cd buzzer_demo && make clean)

